### ISSUE TITLE
some feedback

### ISSUE THREAD

**Issue by hbakhtiyor** [spectresearch/detectem#4]
i think it's bad idea to run splash container from the code, and better to throw error with friendly message to run it.

**Comment by csalazar** [comment]
I think if it's a small project and want to attract people, it has to run smoothly without that many requirements. Your PR creates a new container every time you run `docker run -d -p 8050:8050 -p 8051:8051 scrapinghub/splash`, then you finish with a lot of containers (check `docker ps -a`). How to know which container is used for *detectem*? You lose the link between the target container and *detectem* if you're running multiple splash containers. If you want to handle your docker setup, there are two variables in `settings.py` to do it: `SETUP_SPLASH` and `SPLASH_URL`.

I've managed to handle the docker container in a clean way with good messages in case of errors, then I think we will keep it.
